[2025-02-27 01:46:05 +0530] [13151] [INFO] Starting gunicorn 23.0.0
[2025-02-27 01:46:05 +0530] [13151] [INFO] Listening at: http://127.0.0.1:8000 (13151)
[2025-02-27 01:46:05 +0530] [13151] [INFO] Using worker: sync
[2025-02-27 01:46:05 +0530] [13155] [INFO] Booting worker with pid: 13155
[2025-02-27 01:46:05 +0530] [13156] [INFO] Booting worker with pid: 13156
[2025-02-27 01:46:05 +0530] [13160] [INFO] Booting worker with pid: 13160
[2025-02-27 01:46:05 +0530] [13161] [INFO] Booting worker with pid: 13161
[2025-02-27 01:51:50 +0530] [13151] [INFO] Handling signal: int
[2025-02-27 01:51:50 +0530] [13156] [INFO] Worker exiting (pid: 13156)
[2025-02-27 01:51:50 +0530] [13155] [INFO] Worker exiting (pid: 13155)
[2025-02-27 01:51:50 +0530] [13161] [INFO] Worker exiting (pid: 13161)
[2025-02-27 01:51:50 +0530] [13160] [INFO] Worker exiting (pid: 13160)
[2025-02-27 01:51:51 +0530] [13151] [INFO] Shutting down: Master
[2025-02-27 01:51:55 +0530] [15139] [INFO] Starting gunicorn 23.0.0
[2025-02-27 01:51:55 +0530] [15139] [INFO] Listening at: http://127.0.0.1:8000 (15139)
[2025-02-27 01:51:55 +0530] [15139] [INFO] Using worker: sync
[2025-02-27 01:51:55 +0530] [15140] [INFO] Booting worker with pid: 15140
[2025-02-27 01:51:55 +0530] [15141] [INFO] Booting worker with pid: 15141
[2025-02-27 01:51:55 +0530] [15142] [INFO] Booting worker with pid: 15142
[2025-02-27 01:51:55 +0530] [15143] [INFO] Booting worker with pid: 15143
[2025-02-27 01:56:00 +0530] [15139] [INFO] Handling signal: int
[2025-02-27 01:56:00 +0530] [15140] [INFO] Worker exiting (pid: 15140)
[2025-02-27 01:56:00 +0530] [15141] [INFO] Worker exiting (pid: 15141)
[2025-02-27 01:56:00 +0530] [15142] [INFO] Worker exiting (pid: 15142)
[2025-02-27 01:56:00 +0530] [15143] [INFO] Worker exiting (pid: 15143)
[2025-02-27 01:56:01 +0530] [15139] [INFO] Shutting down: Master
[2025-02-27 01:56:11 +0530] [16340] [INFO] Starting gunicorn 23.0.0
[2025-02-27 01:56:11 +0530] [16340] [INFO] Listening at: http://127.0.0.1:8000 (16340)
[2025-02-27 01:56:11 +0530] [16340] [INFO] Using worker: sync
[2025-02-27 01:56:11 +0530] [16341] [INFO] Booting worker with pid: 16341
[2025-02-27 01:56:11 +0530] [16342] [INFO] Booting worker with pid: 16342
[2025-02-27 01:56:11 +0530] [16346] [INFO] Booting worker with pid: 16346
[2025-02-27 01:56:11 +0530] [16347] [INFO] Booting worker with pid: 16347
[2025-02-27 01:59:32 +0530] [16340] [INFO] Handling signal: int
[2025-02-27 01:59:32 +0530] [16341] [INFO] Worker exiting (pid: 16341)
[2025-02-27 01:59:32 +0530] [16347] [INFO] Worker exiting (pid: 16347)
[2025-02-27 01:59:32 +0530] [16342] [INFO] Worker exiting (pid: 16342)
[2025-02-27 01:59:32 +0530] [16346] [INFO] Worker exiting (pid: 16346)
[2025-02-27 01:59:33 +0530] [16340] [INFO] Shutting down: Master
[2025-02-27 02:00:18 +0530] [17472] [INFO] Starting gunicorn 23.0.0
[2025-02-27 02:00:18 +0530] [17472] [INFO] Listening at: http://127.0.0.1:8000 (17472)
[2025-02-27 02:00:18 +0530] [17472] [INFO] Using worker: sync
[2025-02-27 02:00:18 +0530] [17473] [INFO] Booting worker with pid: 17473
[2025-02-27 02:00:18 +0530] [17474] [INFO] Booting worker with pid: 17474
[2025-02-27 02:00:18 +0530] [17475] [INFO] Booting worker with pid: 17475
[2025-02-27 02:00:18 +0530] [17476] [INFO] Booting worker with pid: 17476
[2025-02-27 15:17:08 +0530] [17472] [INFO] Handling signal: winch
[2025-02-27 15:17:28 +0530] [17472] [INFO] Handling signal: winch
[2025-02-27 15:26:29 +0530] [17472] [INFO] Handling signal: int
[2025-02-27 15:26:29 +0530] [17476] [INFO] Worker exiting (pid: 17476)
[2025-02-27 15:26:29 +0530] [17473] [INFO] Worker exiting (pid: 17473)
[2025-02-27 15:26:29 +0530] [17475] [INFO] Worker exiting (pid: 17475)
[2025-02-27 15:26:29 +0530] [17474] [INFO] Worker exiting (pid: 17474)
[2025-02-27 15:26:30 +0530] [17472] [INFO] Shutting down: Master
[2025-02-27 15:26:41 +0530] [21974] [INFO] Starting gunicorn 23.0.0
[2025-02-27 15:26:41 +0530] [21974] [INFO] Listening at: http://127.0.0.1:8000 (21974)
[2025-02-27 15:26:41 +0530] [21974] [INFO] Using worker: sync
[2025-02-27 15:26:41 +0530] [21975] [INFO] Booting worker with pid: 21975
[2025-02-27 15:26:41 +0530] [21976] [INFO] Booting worker with pid: 21976
[2025-02-27 15:26:41 +0530] [21977] [INFO] Booting worker with pid: 21977
[2025-02-27 15:26:41 +0530] [21978] [INFO] Booting worker with pid: 21978
[2025-02-27 15:26:45 +0530] [21976] [ERROR] Error handling request /memberlist
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/forum/memberlist.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/forum/views.py", line 651, in get
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/forum/memberlist.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:45 +0530] [21976] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/forum/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/forum/views.py", line 89, in get
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/forum/index.html", line 1, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:45 +0530] [21975] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/page_not_found.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 397, in page_not_found
    return render_template("errors/page_not_found.html"), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:45 +0530] [21978] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/page_not_found.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 397, in page_not_found
    return render_template("errors/page_not_found.html"), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:49 +0530] [21977] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/forum/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/forum/views.py", line 89, in get
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/forum/index.html", line 1, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:49 +0530] [21975] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/page_not_found.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 397, in page_not_found
    return render_template("errors/page_not_found.html"), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:49 +0530] [21975] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/forum/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/forum/views.py", line 89, in get
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/forum/index.html", line 1, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:49 +0530] [21976] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/page_not_found.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 397, in page_not_found
    return render_template("errors/page_not_found.html"), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:50 +0530] [21977] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/forum/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/forum/views.py", line 89, in get
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/forum/index.html", line 1, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:50 +0530] [21975] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/page_not_found.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 397, in page_not_found
    return render_template("errors/page_not_found.html"), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:50 +0530] [21976] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/forum/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/forum/views.py", line 89, in get
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/forum/index.html", line 1, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:26:50 +0530] [21978] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/page_not_found.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 397, in page_not_found
    return render_template("errors/page_not_found.html"), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 148, in render_theme_template
    return render_template("_themes/%s/%s" % (theme, template_name), **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _themes/aurora/errors/server_error.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/app.py", line 401, in server_error_page
    return render_template("errors/server_error.html"), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/utils/helpers.py", line 111, in render_template
    return render_theme_template(theme, template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask_themes2/__init__.py", line 151, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/errors/server_error.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 28, in top-level template code
    {% block css %}
  File "/home/aryan/lastgasp/flaskbb/flaskbb/templates/layout.html", line 29, in block 'css'
    {{ super() }}
  File "/home/aryan/lastgasp/flaskbb/.venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'css'.
[2025-02-27 15:27:39 +0530] [21974] [INFO] Handling signal: int
[2025-02-27 15:27:39 +0530] [21978] [INFO] Worker exiting (pid: 21978)
[2025-02-27 15:27:39 +0530] [21977] [INFO] Worker exiting (pid: 21977)
[2025-02-27 15:27:39 +0530] [21975] [INFO] Worker exiting (pid: 21975)
[2025-02-27 15:27:39 +0530] [21976] [INFO] Worker exiting (pid: 21976)
[2025-02-27 15:27:40 +0530] [21974] [INFO] Shutting down: Master
